### ISSUE TITLE
[enhancement] Surface Run Query keyboard shortcut 

### ISSUE THREAD

**Issue by morenoh149** [AlisdairO/pgexercises#15]
It'd be nice to press 'shift+enter' or similar inside the query textarea to Run the Query.

**Comment by miketheman** [comment]
> Alt-r: Run query

https://github.com/AlisdairO/pgexercises/blob/ae5b46d84d5e4cdb6af49047960d7abd76e80f30/site/website/js/site.js#L109-L110

**Comment by morenoh149** [comment]
ah nice! Then lets add some alt text when a user hovers over the `Run Query` button.

**Comment by morenoh149** [comment]
looks like it's already documented in the help screen. Wasn't obvious to me.
