### ISSUE TITLE
Aggregates / Fachours3 - Rounding

### ISSUE THREAD

**Issue by andyw8** [AlisdairO/pgexercises#24]
I'm curious why the solution uses:

`trim(to_char(sum(bks.slots)/2.0, '9999999999999999D99'))`

rather than the simpler:

`round(sum(bks.slots) / 2.0, 2)`

Am I missing some downside?

**Comment by AlisdairO** [comment]
to_char is the generally recommended solution, as it's reliable in all situations: http://stackoverflow.com/questions/13113096/how-to-round-an-average-to-2-decimal-places-in-postgresql .  Thanks a lot for taking a look and raising the issue!
