### ISSUE TITLE
Update Postgres doc links to 9.5

### ISSUE THREAD

**Issue by AlisdairO** [AlisdairO/pgexercises#25]
There's currently a mishmash of 9.2 and 9.3 links

**Comment by anayrat** [comment]
You should use "current" version : 
https://www.postgresql.org/docs/current/static/index.html

**Comment by AlisdairO** [comment]
Thank you, good idea.  Finally getting back in the saddle after moving, thought I'd start with an easy one :-).

**Comment by AlisdairO** [comment]
Fixed by a4107f7edc76156fb2e308ffc3a0d29ffbf899ad
