### ISSUE TITLE
Bad SQL dump

### ISSUE THREAD

**Issue by benjamin-thomas** [AlisdairO/pgexercises#28]
Strange, 

I can see [you've fixed this](https://github.com/AlisdairO/pgexercises/commit/a6de8734d8a67ac2c05745b107dfa5cd7f8128b4), but if I download from either:

- https://raw.githubusercontent.com/AlisdairO/pgexercises/master/site/website/dbfiles/clubdata.sql
- https://www.pgexercises.com/dbfiles/clubdata.sql

I still get that badly formatted line (space separated, not tabs separated)

**Comment by AlisdairO** [comment]
Hey, sorry for the delay getting back to you!  I'll look to fix this up this weekend, thanks for letting me know.

**Comment by benjamin-thomas** [comment]
No problem :)
Le sam. 3 déc. 2016 à 23:57, Alisdair Owens <notifications@github.com> a
écrit :

**Comment by AlisdairO** [comment]
So maybe a few weeks later, but this is sorted out now :-).  Commit 8140e533d7333cec5712d55bbe02ce858e36d188 .  Thanks a lot for both the report and your patience!

**Comment by benjamin-thomas** [comment]
Hello @AlisdairO 

With that typo sorted out, I've setup a little repo, to make loading a test database easy and fast.

If you're interested, I could send you a pull request?

https://github.com/benjamin-thomas/pgexercises

**Comment by AlisdairO** [comment]
Hey,

I’d certainly be interested. There’s a docker file in there already that someone contributed, which is more complicated than this (it’s for a whole development environment). I think this would be nice for people who just want to set up the test database, but would it be possible to make it load the SQL file as well?

Many thanks, and sorry for the delayed reply,
-Alisdair
