### ISSUE TITLE
Add a sub-query option

### ISSUE THREAD

**Issue by dimidd** [AlisdairO/pgexercises#31]
Hi, I've solved [this exercise](https://github.com/AlisdairO/pgexercises/blob/master/questions/joins/00030000-self.ex) using a sub-query instead of a join:
`select distinct cd.members.firstname, cd.members.surname
   from cd.members
   where cd.members.memid in (select distinct cd.members.recommendedby
						   from cd.members)
   order by cd.members.surname;`

And I wonder if it makes sense to add it as another option to the explanation, since this this section deals with joins.

**Comment by AlisdairO** [comment]
Hey, this is a perfectly reasonable approach to the problem, but as I recall I haven't really introduced subqueries at this point - so I'd rather avoid overloading the reader.

Thanks a lot for raising the issue, I appreciate your input!
