### ISSUE TITLE
Joins - self join 2 right answer seemingly incorrect

### ISSUE THREAD

**Issue by kennes913** [AlisdairO/pgexercises#34]
URL: https://www.pgexercises.com/questions/joins/self2.html

Question is **How can you output a list of all members, including the individual who recommended them (if any)? Ensure that results are ordered by (surname, firstname).**

**memfname, memsname** combinations should be unique by nature of question, but I see this in the correct response:

<img width="384" alt="screen shot 2017-10-23 at 5 15 27 pm" src="https://user-images.githubusercontent.com/7109431/31915970-32ef565c-b816-11e7-856b-cb9404c8d904.png">

**Comment by AlisdairO** [comment]
Hey, in this case, the issue you're running into is that there are two members named 'Darren Smith' in the dataset, so it's correct for this case.
