### ISSUE TITLE
Unique exercise has wrong result

### ISSUE THREAD

**Issue by snoobvn** [AlisdairO/pgexercises#36]
https://www.pgexercises.com/questions/basic/unique.html
Here is the expected result:
```
surname
--
Bader
Baker
Boothe
Butters
Coplin
Crumpet
Dare
Farrell
GUEST
Genting
```

Here is the actual result: (the result is get from your answer)
```
surname
--
Bader
Baker
Boothe
Butters
Coplin
Crumpet
Dare
Farrell
Genting
GUEST
```

**Comment by AlisdairO** [comment]
Ah, thanks a lot for the catch. This was the result of an operational screwup when updating the postgres database version. Fixed now.
