### ISSUE TITLE
Simple aggregation exercises doesn't validate column name

### ISSUE THREAD

**Issue by dleve123** [AlisdairO/pgexercises#40]
Currently, an acceptable answer to the [simple aggregation exercise](https://www.pgexercises.com/questions/basic/agg.html) is:

```sql
SELECT max(joindate)
FROM cd.members;
```

which notably doesn't include an `as latest` in the `SELECT` clause.

I wanted to flag this incase the maintainer wanted to be strict about what exactly constitutes a correct answer. IMO, it's valuable to be strict here considering pgexercises is all about learning new topics.

If interested in correcting, I'm happy to help if pointed in the right direction!

**Comment by AlisdairO** [comment]
Hey, in this case I don't want to be over-strict about validating - I tend to think it'll frustrate users who get the gist of the idea but forget to label columns appropriately. Thanks for getting in touch and my apologies for the absurdly late response.
