### ISSUE TITLE
No `trim` hint for Aggregates / fachours3 exercise 

### ISSUE THREAD

**Issue by T1mL3arn** [AlisdairO/pgexercises#51]
There is no info about using `trim` function in the hint (for [Aggregates / fachours3 exercise](https://www.pgexercises.com/questions/aggregates/fachours3.html). Visually, the query
```sql
select
	f.facid, f.name,
	to_char(sum(b.slots) * 0.5, '999.99') as hours
from cd.bookings as b
join cd.facilities as f on b.facid = f.facid
group by f.facid, f.name
order by f.facid asc
;
```
gives an answer that looks like the expected one. But due spaces it is a wrong answer. It took a quite time for me to figure out why is my query wrong. (I gave up and pressed `Answer` button :sweat_smile: )

**Comment by AlisdairO** [comment]
Good call, thanks! fixed in 128c40e29d091d808bd27d0c578ce54c7ee694d7
