### ISSUE TITLE
Guests are falsely counted as member in Members1

### ISSUE THREAD

**Issue by corneliusroemer** [AlisdairO/pgexercises#54]
Question
Find the total number of members who have made at least one booking.

Model Answer
`select count(distinct memid) from cd.bookings `

Problem
This counts the guest user with memid=0 as a member, this is logically wrong, since a guest is by definition not a member. Either question has to be reworded or model answer updated with `where memid != 0`

**Comment by AlisdairO** [comment]
Thanks - corrected in 866793fc26272cbdcbb06aada2338a5ab2f13cb1
