### ISSUE TITLE
Wrong wording: Question  Fachours1a should ask for slots not hours

### ISSUE THREAD

**Issue by corneliusroemer** [AlisdairO/pgexercises#55]
Question
Produce a list of facilities with more than 1000 slots booked. Produce an output table consisting of facility id and hours, sorted by facility id.

Expected Result
Lists currently "Total Slots"

Problem
Question asks for hours (one slot is apparently 30min, mentioned somewhere else) but answers with slots -> inconsistent

**Comment by AlisdairO** [comment]
Good call, thanks! Resolved by f103b200a57293ee1e6968600bf636475780f09c
