### ISSUE TITLE
Wrong answer is accepted as correct

### ISSUE THREAD

**Issue by ilbonte** [AlisdairO/pgexercises#66]
First of all thanks for your work, it's helping a lot :) 

On the exercise [Threejoin](https://pgexercises.com/questions/joins/threejoin.html) I've submitted a wrong answers (I've forgot to order the results), but the answer has been evaluated as correct.

My answer:

```sql
select distinct (m.firstname || ' ' || m.surname ) as member, f.name as facility
from cd.members m join cd.bookings b using(memid) join cd.facilities f using (facid)
where f.name like '%Tennis Court%'
```

You can see in the screenshot below that my answer and the expected result differ.

![image](https://user-images.githubusercontent.com/7412876/96462275-aff39c00-1225-11eb-996e-2f64ccdd89d3.png)

**Comment by AlisdairO** [comment]
Thanks! I'll take a look.

**Comment by AlisdairO** [comment]
Thanks for the heads up - this exercise should be fixed now, although I'll need to work out what to do with the following exercise - currently the pgexercises software supports exact sorting or no sorting, but doesn't handle a requirement for partial sorting...

Hope the site continues to be useful for you :)
