### ISSUE TITLE
No confirmation for re-running a successful query

### ISSUE THREAD

**Issue by jschaf** [AlisdairO/pgexercises#7]
First off, amazingly helpful site.

Here's a small pain point I'm experiencing:

After I get the correct answer, I often like to experiment with the query to find other alternate techniques.  If I run another successful query there's no indication that anything happened.

My suggestion:

Clear the output before another query is run.

**Comment by AlisdairO** [comment]
Hey - glad you're finding it useful!  I'm not quite sure I understand what you're looking for - the queries generally run fairly quickly so if I clear just before the query is run, there might be no more than a flicker on the screen to indicate that the results have changed.  Is that enough for your needs, or am I misunderstanding?

**Comment by jschaf** [comment]
The problem is that there's no flicker if you have another successful query.  There's no indication that anything happened.  Here's a quick example.  There's no positive feedback that my query with the `facs` alias was successful.  I know that it probably worked because it didn't error out, but it'd be nice to know that it was successful.

![No Flicker Image](http://i.imgur.com/uHumBYm.gif)

**Comment by AlisdairO** [comment]
Fair enough - that shouldn't be very hard to implement!  I'm away for the next week or so but I'll add it to the list.

**Comment by AlisdairO** [comment]
Apologies for the interminable delay in fixing this - real life has been rather busy of late!  Hopefully you should find this issue is fixed now - and thanks for your help.

**Comment by jschaf** [comment]
No worries, thanks for the fix.
